name: Create transparency report for posts

on:
  workflow_dispatch:
  push:
    paths: 
      - .github/workflows/post-transparency.yaml
      - _posts/**

jobs:
  audit-pdf:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v1.4.4
        with:
          subject-path: .github/workflows/post-transparency.yaml, _posts/**
